on:
  push:
    branches: [master]
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: ðŸ”¨ Build Project
        run: |
          npm install
          npm run build

      - name: Simple FTP deploy
  # You may pin to the exact commit or the version.
  # uses: kevinpainchaud/simple-ftp-deploy-action@2c6e7dfe809abd4f8f687a78b5d79efaf5c439ad
  uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
  with:
    # FTP host
    ftp_host: ftp.hostde30.fornex.host
    # FTP username
    ftp_username: denis@den-kaz.com
    # FTP password
    ftp_password: ${{ secrets.password }}
    # The local folder to copy
    local_source_dir: build
    # The remote folder
    dist_target_dir: /
    # Delete files not present in the local folder on the remote folder
    delete: # optional, default is false
    # Download only newer files
    only_newer: # optional, default is false
    # Ignore time when deciding whether to download
    ignore_time: # optional, default is false
    # Ignore file(s) and/or directorie(s)
    exclude: # optional, default is
    # Disable SSL certificate verification
    disable_ssl_certificate_verification: # optional, default is true
    # Optional raw string of flags for lftp eg. --no-empty-dirs
    other_flags: # optional, default is
